### ISSUE TITLE
ToDo for release

### ISSUE THREAD

**Issue by goiwai** [goiwai/nagoya-puppet#1]
- [x] WebDAV TPC (streamed) の確認
- [x] info へのアクセス確認 (VOMS)
- [x] info へのアクセス確認 (browser) ←なんかできねえな、なんか仕掛けてたんだっけ？
- [x] wiki.kek.jp で編集出来るか確認
- [x] wiki 変数テーブル更新
- [x] README.md 更新 (select one of wiki hosted at desy or wiki)
- [x] release tag v1.1.0 付与

**Comment by goiwai** [comment]
All TODOs done.
